# Generated by Django 2.1 on 2018-09-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_product_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_description',
            new_name='description',
        ),
    ]
